from tkinter import *
window = Tk()
window.title("Welcome to Tkinter")
window.geometry("300x300")
greet = Label(text = "Welcome!", fg = "blue", bg = "lightgreen")
button = Button(text = "Click Here!", fg = "white", bg = "black")
entry = Entry(fg = "black", bg = "white", width = 50)
greet.pack()
button.pack()
entry.pack()
frame = Frame(master = window, relief = RAISED, borderwidth = 5)
frame.pack()
textbox = Text(fg = "yellow", bg = "brown")
textbox.pack()
window.mainloop()